config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show] do
    resources :goals, only: [:new]
  end

  resources :goals, only: [:show, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :body, :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :ensure_session_token

  attr_reader :password

  has_many :goals

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password

    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def resest_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def login!(user)
    session[:session_token] = user.resest_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def create
    goal = Goal.new(goal_params)

    if goal.save
      redirect_to user_url(goal)
    else
      flash[:errors] = goal.errors.full_messages
      redirect_to new_user_goal_url
    end
  end

  def new
    render :new
  end

  def show
  end

  def destroy
  end

  private
  def goal_params
    params.require(:goal).permit(:user_id, :body, :public, :completed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = ['Invalid Credentials']
      redirect_to new_session_url
    end
  end

  def destroy
    user = User.find(current_user.id)
    user.resest_session_token!
    session[:session_token] = nil

    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)

    if user.save
      login!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])

    if @user
      render :show
    else
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goals/new.html.erb
<h1>Create new goal!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form class="" action="<%= users_url  %>" method="post">
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="submit">
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<form class="" action="<%= session_url %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="submit" name="" value="Log Out">
</form>